image: node:18

stages:
  - install
  - build
  - test
  - security
  - deploy

variables:
  APP_DIR: "frontend"  # Explicitly point to your React subdirectory

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${APP_DIR}/node_modules/  # Cache specific to frontend directory

install_dependencies:
  stage: install
  script:
    - cd ${APP_DIR}  # Critical: Change to frontend directory first
    - npm install
    - npm audit --production
  artifacts:
    paths:
      - ${APP_DIR}/node_modules/
  tags:
    - docker

build_app:
  stage: build
  script:
    - cd ${APP_DIR}
    - npm run build
  artifacts:
    paths:
      - ${APP_DIR}/build/  # React uses 'build' folder
    expire_in: 1 week
  tags:
    - docker

unit_tests:
  stage: test
  script:
    - cd ${APP_DIR}
    - CI=true npm test  # Required for React in CI environments
  tags:
    - docker

lint_code:
  stage: test
  script:
    - cd ${APP_DIR}
    - npm run lint
  tags:
    - docker

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: "${APP_DIR}/node_modules,${APP_DIR}/build"
  tags:
    - docker

deploy_to_pages:
  stage: deploy
  script:
    - cd ${APP_DIR}
    - mkdir -p public
    - cp -r build/* public/  # Copy React build output
  artifacts:
    paths:
      - public
  only:
    - main
  tags:
    - docker