image: node:18  # Uses Docker container with Node pre-installed

stages:
  - install
  - build
  - test
  - security

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_deps:
  stage: install
  script:
    - npm install
    - npm audit --production
  artifacts:
    paths:
      - node_modules/

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

unit_tests:
  stage: test
  script:
    - npm test -- --watch=false --browsers=ChromeHeadless

lint_code:
  stage: test
  script:
    - npm run lint

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: "node_modules,dist"